GET http://localhost:3000/api/auth/test

###

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "nickname" : "jieun8",
    "email" : "jieun8@test.com",
    "password":"password"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email" : "jieun3@test.com",
    "password":"diff"
}

###
POST http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NWI0NDgzZS0zNjM4LTRmODEtOGVlZS1iNmEyNjFkODI4YmUiLCJpYXQiOjE3MTY3Nzg2NjIsImV4cCI6MTcxNjg2NTA2Mn0.6nY5Cc8YbgeaJIyfbCWKMJp7I56u6vnk-KNrd8YFh98

###
POST http://localhost:3000/api/auth/refresh
Content-Type: application/json

{
   "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NWI0NDgzZS0zNjM4LTRmODEtOGVlZS1iNmEyNjFkODI4YmUiLCJpYXQiOjE3MTY3Nzk1NjYsImV4cCI6MTcxNjc3OTYyNn0.NFYJONmg06sBRo8gDL8AG6Wl_QLi8XbmtuI0aPPmqj4"
}